config/routes.rb
Rails.application.routes.draw do
  

  get 'users/new'

  get 'static_pages/home'
  get 'help'=>'static_pages#help'
  get 'contact'=> 'static_pages#contact'
  get 'about'=>'static_pages#about'
  get  'sign_up'=> 'users#new'
  resources :users

  root 'static_pages#home'

end

app/models/user.rb
class User < ActiveRecord::Base

validates :name , presence: true
validates :email, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def contact
  end

  def about
  	
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  


  def new
  end

  def show
  	@user= User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title)%> | BlogTdd</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title,"About")%>		

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact")%>		

app/views/static_pages/help.html.erb
<% provide(:title,"Help")%>
<div class="container">
	<div id="cosas"><h1>Help!</h1></div>
<%=link_to "home",root_path%>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<h1>Home</h1>
<h3><%=	link_to 'Ayuda',help_path%></h3>

app/views/users/new.html.erb
<% provide(:title,"Sign Up!") %>
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<% provide(:title,@user.name) %>
<%=@user.name%>